import type { NavbarConfig } from '@vuepress/theme-default'

export const navbarZh: NavbarConfig = [
    { text: '首页', link: '/', },
    { text: 'myNotes', link: '/qscaler/01 html/1 基础篇.html', },
    { text: 'onlineNotes', link: '/online/1 基础进阶/1.基础篇.html', },
    {
        text: '更多',
        children: [
            {
                text: '其他',
                children: [
                    { text: '博文动态', link: 'http://blog.poetries.top/archives/', },
                    { text: 'Handbook', link: 'https://blog.poetries.top/handbook', },
                    { text: '职场话题', link: 'https://topics.poetries.top', },
                    { text: 'CSS可视化', link: 'https://blog.poetries.top/css-reference', },
                ]
            },
        ]
    },
    {
        text: '文档',
        children: [
            {
                text: '框架文档',
                children: [
                    { text: 'React', link: 'https://react.docschina.org/', },
                    { text: 'Vue3', link: 'https://v3.cn.vuejs.org/', },
                    { text: 'Vite', link: 'https://vitejs.cn/', },
                    { text: 'Svelte', link: 'https://www.sveltejs.cn/', },
                    { text: 'Angular', link: 'https://www.angularjs.net.cn/', },
                    { text: 'NodeJS', link: 'https://nodejs.org/en/docs/', },
                    { text: 'Egg', link: 'https://www.eggjs.org/zh-CN', },
                    { text: 'Nest', link: 'https://docs.nestjs.cn/8/introduction', },
                    { text: 'Koa', link: 'https://koa.bootcss.com/', },
                    { text: 'Express', link: 'https://www.expressjs.com.cn/', },
                    { text: 'Electron', link: 'https://www.electronjs.org/zh/docs/latest/', },
                    { text: 'Ionic', link: 'http://www.ionic.wang/components_doc-index.html', },
                    { text: 'Taro', link: 'https://taro-docs.jd.com/taro/docs/', },
                    { text: 'Uniapp', link: 'https://uniapp.dcloud.io/', },
                    { text: 'React Native', link: 'https://reactnative.cn/', },
                    { text: 'Webpack', link: 'https://www.webpackjs.com/', },
                    { text: 'Rollup', link: 'https://www.rollupjs.com/', },
                    { text: 'Jquery API', link: 'https://jquery.cuishifeng.cn/', },
                    { text: 'Bootstrap', link: 'https://bootstrapcreative.com/resources/bootstrap-4-css-classes-index/', },
                    { text: 'Axios', link: 'https://www.axios-http.cn/', },
                    { text: 'Lodash', link: 'https://www.lodashjs.com/', },
                    { text: 'RXJS', link: 'https://cn.rx.js.org/', },
                    { text: 'Sequelize', link: 'https://www.sequelize.com.cn/', },
                    { text: 'TypeORM', link: 'https://typeorm.biunav.com/zh', },
                    { text: 'Mongoose', link: 'https://mongoosejs.com/docs/guide.html', },
                    { text: 'GraphQL', link: 'https://graphql.cn/', },
                    { text: 'Puppeteer', link: 'https://zhaoqize.github.io/puppeteer-api-zh_CN', },
                    { text: 'Sass', link: 'https://www.sass.hk/', },
                    { text: 'Less', link: 'https://less.bootcss.com/', },
                    { text: 'Umi4', link: 'https://umijs.org/', },
                    { text: 'Miniprogram', link: 'https://developers.weixin.qq.com/miniprogram/dev/framework/config.html', },
                ],
            },
            {
                text: '文档教程',
                children: [
                    { text: 'Cheatsheets', link: 'https://devhints.io/', },
                    { text: 'Devdocs有可能是全球最全的文档库', link: 'https://devdocs.io/', },
                    { text: 'Overapi', link: 'https://overapi.com/', },
                    { text: 'JavaScript 标准参考教程', link: 'http://javascript.ruanyifeng.com/', },
                    { text: 'ES6 入门教程', link: 'https://es6.ruanyifeng.com/', },
                    { text: 'MND在线文档', link: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript', },
                    { text: 'Typscript中文文档', link: 'https://www.typescriptlang.org/zh/tsconfig', },
                    { text: 'JavaScript Promise迷你书（中文版）', link: 'http://liubin.org/promises-book/#introductiono', },
                    { text: 'Canvas API中文', link: 'https://www.canvasapi.cn/', },
                    { text: 'Git中文手册', link: 'https://git-scm.com/book/zh/v2', },
                    { text: '云开发Cloudbase', link: 'https://docs.cloudbase.net/', },
                    { text: 'Serverless中文文档', link: 'https://cn.serverless.com/', },
                ],
            },
            {
                text: 'UI组件',
                children: [
                    { text: 'Ant Design React', link: 'https://ant.design', },
                    { text: 'Ant Design Vue', link: 'https://www.antdv.com/components/overview', },
                    { text: 'Ant Design Pro', link: 'https://pro.ant.design/zh-CN/', },
                    { text: 'ProComponents', link: 'https://procomponents.ant.design/components', },
                    { text: '腾讯Tdesign', link: 'https://tdesign.tencent.com/', },
                    { text: 'NutUI京东风格的轻量级移动端 Vue 组件库', link: 'https://nutui.jd.com/', },
                    { text: 'Semantic UI Vue', link: 'https://semantic-ui-vue.github.io/', },
                    { text: 'Cube UI Vue滴滴', link: 'https://didi.github.io/cube-ui/', },
                    { text: 'Iview UI', link: 'https://www.iviewui.com/', },
                    { text: '有赞Vant Vue3', link: 'https://vant-contrib.gitee.io/vant/', },
                    { text: '有赞Vant 小程序', link: 'https://youzan.github.io/vant-weapp', },
                    { text: 'Element UI Vue3', link: 'https://element-plus.gitee.io/zh-CN/', },
                ],
            },
            {
                text: '可视化',
                children: [
                    { text: 'Antv', link: 'https://antv.gitee.io/zh/', },
                    { text: 'Bizcharts', link: 'https://www.bizcharts.net/', },
                    { text: 'Threejs', link: 'https://threejs.org/', },
                    { text: 'D3js', link: 'https://d3js.org/', },
                    { text: 'Highcharts', link: 'https://www.highcharts.com.cn/', },
                    { text: 'Echarts', link: 'https://echarts.apache.org/zh/index.html', },
                ],
            },
            {
                text: '配置相关',
                children: [
                    { text: 'ESLint', link: 'https://cn.eslint.org/docs/user-guide/getting-started', },
                    { text: 'Babel', link: 'https://www.babeljs.cn/', },
                    { text: 'Nginx中文文档', link: 'https://www.nginx.cn/doc/index.html', },
                    { text: 'Github Action中文', link: 'https://docs.github.com/cn/actions', },
                    { text: 'Docker官方文档', link: 'https://docs.docker.com/get-started/', },
                    { text: 'Jenkins官方文档', link: 'https://www.jenkins.io/zh/doc/', },
                ],
            },
            {
                text: '后端相关',
                children: [

                    { text: 'Spring官方文档中文版', link: 'https://www.springcloud.cc/spring-reference.html', },
                    { text: 'Spring Boot官方文档', link: 'https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/', },
                    { text: 'Spring Cloud官方文档', link: 'https://spring.io/projects/spring-cloud', },
                    { text: 'Java8官方文档', link: 'https://docs.oracle.com/javase/8/docs/api/index.html', },
                    { text: 'maven官方文档', link: 'https://maven.apache.org/guides/', },
                    { text: 'Tomcat 8官方文档', link: 'https://tomcat.apache.org/tomcat-8.0-doc/index.html', },
                    { text: 'Kafka中文文档', link: 'https://kafka.apachecn.org/', },
                    { text: 'MyBatis中文文档', link: 'https://mybatis.org/mybatis-3/zh/index.html', },
                    { text: 'RabbitMQ中文文档', link: 'https://www.rabbitmq.com/documentation.html', },
                    { text: 'Dubbo中文文档', link: 'https://dubbo.apache.org/zh/docs/', },
                    { text: 'Netty官方文档', link: 'https://netty.io/wiki/index.html', },
                    { text: 'Elasticsearch官方文档', link: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html', },
                    { text: 'K8S官方文档', link: 'https://kubernetes.io/zh-cn/docs/home/', },
                ],
            },
        ],
    },
    {
        text: '工具',
        children: [
            { text: '前端综合导航', link: 'https://nav.poetries.top/', },
            {
                text: '实用工具',
                children: [
                    { text: '正则表达式', link: 'https://geek-docs.com/regexp/regexp-tutorials/21_regular_expression_and.html', },
                    { text: '在线正则表达式调试工具', link: 'https://regexr.com/', },
                    { text: '在线正则表达式调试工具', link: 'https://regexr.com/', },
                    { text: '在线正则表达式可视化', link: 'https://jex.im/regulex/#!flags=&amp;re=%5E(a%7Cb)%3F%24', },
                    { text: '常用正则表达式大全', link: 'https://any86.github.io/any-rule/', },
                    { text: '可以在线看代码流程的网站：loupe', link: 'http://latentflip.com/loupe', },
                    { text: '在线MD5编码工具', link: 'https://www.zxgj.cn/g/md5', },
                    { text: '在线JWT解码工具', link: 'http://jwt.calebb.net/', },
                    { text: '在线JSON解析', link: 'https://www.json.cn/', },
                    { text: '在线文本比对', link: 'https://www.fly63.com/tool/textdiff/', },
                    { text: '在线JS代码格式化', link: 'https://prettier.io/playground/', },
                    { text: '在线SQL压缩格式化', link: 'https://www.zxgj.cn/g/sqlformat', },
                    { text: '在线XML压缩格式化', link: 'https://www.zxgj.cn/g/xmlformat', },
                    { text: '在线时间戳转化工具', link: 'https://www.zxgj.cn/g/unix', },
                    { text: '在线RGB颜色转化工具', link: 'https://www.zxgj.cn/g/yansezhi', },
                    { text: '在线HTTP在线接口测试工具', link: 'https://www.fly63.com/php/http/', },
                    { text: '在线IP地址查询', link: 'https://www.ipip.net/ip.html', },
                    { text: '在线菜鸟综合导航工具', link: 'https://c.runoob.com/', },
                ],
            },
            {
                text: '在线编程',
                children: [
                    { text: 'MipCode快速的在线代码创作工具', link: 'http://www.mipcode.com/', },
                    { text: 'Codepen', link: 'https://codepen.io/', },
                    { text: 'Jsbin', link: 'http://jsbin.com/', },
                    { text: 'CodeSandBox在线快速学习React/Vue', link: 'https://codesandbox.io/', },
                    { text: 'Vue SFC Playground', link: 'https://sfc.vuejs.org/', },
                    { text: 'Vue3 模板在线解析查看编译结果', link: 'https://vue-next-template-explorer.netlify.app/', },
                    { text: 'Svelte Playground', link: 'https://www.sveltejs.cn/examples#hello-world', },
                    { text: '在线尝试Babel编译', link: 'https://babeljs.io/repl', },
                    { text: 'Typescript在线编译', link: 'https://www.tslang.cn/play/index.html', },
                    { text: 'AST可视化编辑', link: 'https://astexplorer.net/', },
                    { text: '在线尝试Rollup打包', link: 'https://rollupjs.org/repl/', },
                    { text: 'Prettier Playground', link: 'https://prettier.io/playground/', },
                    { text: 'Stackblitz基于VSCODE的WEBIDE', link: 'https://stackblitz.com/', },
                    { text: 'NPM Runkit在浏览器中快速学习及尝试Node.js模块', link: 'https://npm.runkit.com/', },
                    { text: 'Play with Docker在线体验', link: 'https://labs.play-with-docker.com/', },
                ],
            },
            {
                text: 'CSS相关',
                children: [
                    { text: '用来帮助大家查找CSS的相关属性的语法，以及使用方法', link: 'https://cssvalues.com/?view=css3', },
                    { text: '提供了CSS相关属性的浏览器兼容表，同时提供了对应属性资源', link: 'http://caniuse.com/', },
                    { text: 'Flex在线动态练习', link: 'http://flexboxfroggy.com/', },
                    { text: '贝塞尔曲线生成工具', link: 'https://cubic-bezier.com/#.17,.67,.83,.67', },
                    { text: 'SCSS在线转CSS', link: 'https://www.sassmeister.com/', },
                    { text: 'Clip-path在线生成器', link: 'http://tools.jb51.net/static/api/css3path/index.html', },
                    { text: 'Animate.css动画效果', link: 'https://animate.style/', },
                    { text: '按需定制CSS动画效果', link: 'https://animista.net/play/basic/scale-up', },
                    { text: '一份清单，按字母表顺序列出了每个CSS属性', link: 'http://www.blooberry.com/indexdot/css/propindex/all.htm', },
                    { text: 'CSS按钮生成器', link: 'https://www.bestcssbuttongenerator.com/#/37', },
                    { text: 'Css3按钮动画', link: 'http://fian.my.id/Waves/#examples', },
                    { text: 'CSS3渐变样式生成器，类似Photoshop中的渐变界面', link: 'http://www.colorzilla.com/gradient-editor', },
                    { text: 'CSS3 Maker可在线演示渐变阴影旋转动画并生成代码', link: 'http://www.css3maker.com', },
                    { text: 'CSS3 Tool非常方便的生成背景渐变、阴影、旋转和边框圆角效果', link: 'http://westciv.com/tools/gradients', },
                    { text: 'SVG背景生成', link: 'https://www.svgbackgrounds.com/#rose-petals', },
                    { text: '多张图片合成雪碧图', link: 'https://www.toptal.com/developers/css/sprite-generator', },
                    { text: '汇集了实现各种加载效果的CSS代码片段', link: 'https://tobiasahlin.com/spinkit/', },
                    { text: 'SVG滤镜', link: 'https://yoksel.github.io/svg-filters/#/docs', },
                    { text: 'HTML5 元素标签含义大全(元素周期表)', link: 'http://www.html5star.com/manual/html5label-meaning/', },
                    { text: 'HTML语义化', link: 'http://justineo.github.io/slideshows/semantic-html', },
                    { text: 'KakaCss快速生成Css样式，在任意网站复制内容，再到本页面Ctrl+V', link: 'https://renzhezhilu.gitee.io/kakacss/', },
                    { text: 'CSS参考手册', link: 'http://css.doyoe.com/', },
                    { text: '各种各样的loading效果', link: 'http://loading.io/', },
                    { text: 'CSS shadow generator', link: 'https://neumorphism.io/', },
                    { text: '通过拖拽的形式生成需要的border radius', link: 'https://shadows.brumm.af/', },
                    { text: '花式半径生成器-通过拖拽的形式生成需要的border radius', link: 'https://9elements.github.io/fancy-border-radius/', },
                    { text: 'cssgrid-generator', link: 'https://cssgrid-generator.netlify.app/', },
                ],
            },

            {
                text: '综合',
                children: [
                    { text: '可视化学习算法网站', link: 'https://algorithm-visualizer.org/branch-and-bound/binary-search', },
                    { text: '在线Nginx配置', link: 'https://www.digitalocean.com/community/tools/nginx?global.app.lang=zhCN', },
                    { text: 'React生命周期查看网站', link: 'https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/', },
                    { text: 'CodeFun设计稿智能生成源代码', link: 'https://code.fun/', },
                    { text: 'Imgcook由设计稿一键智能生成代码的大厨', link: 'https://www.imgcook.com/', },
                ],
            },
            {
                text: '创作必备',
                children: [
                    { text: '在线画图processon', link: 'https://www.processon.com/', },
                    { text: 'Draw.io免费的流行的流程图工具', link: 'https://app.diagrams.net/', },
                    { text: '在线思维导图mindline', link: 'http://www.mindline.cn/webapp', },
                    { text: '在线字数统计', link: 'https://www.eteste.com/', },
                    { text: '在线mardown排版', link: 'https://mdnice.com/', },
                    { text: '在线免费图床', link: 'https://sm.ms/', },
                    { text: '在线代码截图carbon', link: 'https://carbon.now.sh/', },
                    { text: '在线短链生成', link: 'http://mrw.so/', },
                    { text: '在线文本替换', link: 'https://www.fly63.com/tool/textreplace/', },
                    { text: '在线文件压缩', link: 'https://docsmall.com/', },
                    { text: '在线多媒体转换器', link: 'https://cn.office-converter.com/', },
                    { text: '在线PDF转化工具SmallPdf', link: 'https://smallpdf.com/cn/pdf-tools', },
                    { text: '在线任意文件的格式转换Convertio', link: 'https://convertio.co/zh/', },
                    { text: '在线PS工具', link: 'https://www.uupoop.com/#/', },
                    { text: '在线抠图工具', link: 'https://www.remove.bg/zh', },
                    { text: 'LOGO在线制作', link: 'https://www.uugai.com/', },
                    { text: '在线制作海报设计工具', link: 'https://www.designcap.com/', },
                    { text: 'Open source icons', link: 'https://feathericons.com/', },
                    { text: '表情包在线网站', link: 'https://fabiaoqing.com/', },
                    { text: '图片智能放大工具', link: 'https://bigjpg.com/', },
                    { text: 'ICO图标在线生成', link: 'https://www.fly63.com/php/ico/', },
                    { text: '视频转GIF工具', link: 'https://www.fly63.com/tool/giftxt/', },
                    { text: '音频在线处理', link: 'https://www.aoqiv.com/', },
                    { text: '多图合成GIF工具', link: 'https://gif.55.la/', },
                    { text: '在线图片压缩工具', link: 'https://tinypng.com/', },
                    { text: 'Pixabay图片素材库', link: 'https://pixabay.com/zh/', },
                    { text: 'Unsplash图片素材库', link: 'https://unsplash.com/', },
                    { text: 'Pexels图片素材库', link: 'https://www.pexels.com/zh-cn/', },
                ],
            },
        ],
    },
]
